# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: 
    - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: ['2.0.x', '3.0', '3.1.x', '5.0.x' ]   
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: check out code
        uses: actions/checkout@v2

      - name: setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1
        with:
            dotnet-version: ${{ matrix.dotnet-version }}
            
      - name: Display dotnet version
        run: dotnet --version
              
      - name: Restore dependencies
        run: dotnet restore ./FirstStaticWebApp/FirstStaticWebApp.csproj

      - name: Build application
        run: dotnet build ./FirstStaticWebApp/FirstStaticWebApp.csproj -c Release --no-restore
